BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TABLE availability_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    teacher_id BIGINT NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_availability_slots PRIMARY KEY (id),
    CONSTRAINT uq_availability_slots_id_teacher UNIQUE (id, teacher_id),
    CONSTRAINT fk_availability_slots_teacher
        FOREIGN KEY (teacher_id)
        REFERENCES users(id),
    CONSTRAINT ck_availability_slots_time
        CHECK (ends_at > starts_at)
);

CREATE INDEX ix_availability_slots_teacher_start
    ON availability_slots (teacher_id, starts_at);

CREATE TABLE booking_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    learner_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    availability_slot_id BIGINT NOT NULL,
    message TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_booking_requests PRIMARY KEY (id),
    CONSTRAINT fk_booking_requests_learner
        FOREIGN KEY (learner_id)
        REFERENCES users(id),
    CONSTRAINT fk_booking_requests_teacher_skill
        FOREIGN KEY (teacher_id, skill_id)
        REFERENCES user_skills(user_id, skill_id),
    CONSTRAINT fk_booking_requests_teacher_slot
        FOREIGN KEY (availability_slot_id, teacher_id)
        REFERENCES availability_slots(id, teacher_id),
    CONSTRAINT ck_booking_requests_different_users
        CHECK (learner_id <> teacher_id),
    CONSTRAINT ck_booking_requests_status
        CHECK (
            status IN (
                'PENDING',
                'ACCEPTED',
                'REJECTED',
                'CANCELLED'
            )
        )
);

CREATE INDEX ix_booking_requests_teacher_status
    ON booking_requests (teacher_id, status);

CREATE INDEX ix_booking_requests_learner
    ON booking_requests (learner_id);

CREATE INDEX ix_booking_requests_teacher_skill
    ON booking_requests (teacher_id, skill_id);

CREATE INDEX ix_booking_requests_slot_teacher
    ON booking_requests (availability_slot_id, teacher_id);

CREATE UNIQUE INDEX uq_booking_requests_accepted_slot
    ON booking_requests (availability_slot_id)
    WHERE status = 'ACCEPTED';

CREATE TRIGGER trg_booking_requests_set_updated_at
BEFORE UPDATE ON booking_requests
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    booking_request_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_sessions PRIMARY KEY (id),
    CONSTRAINT uq_sessions_booking_request UNIQUE (booking_request_id),
    CONSTRAINT fk_sessions_booking_request
        FOREIGN KEY (booking_request_id)
        REFERENCES booking_requests(id),
    CONSTRAINT ck_sessions_status
        CHECK (
            status IN (
                'SCHEDULED',
                'COMPLETED',
                'CANCELLED'
            )
        ),
    CONSTRAINT ck_sessions_completed_at
        CHECK (
            (status = 'COMPLETED' AND completed_at IS NOT NULL)
            OR
            (status <> 'COMPLETED' AND completed_at IS NULL)
        )
);

CREATE TRIGGER trg_sessions_set_updated_at
BEFORE UPDATE ON sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT NOT NULL,
    rating SMALLINT NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT uq_reviews_session UNIQUE (session_id),
    CONSTRAINT fk_reviews_session
        FOREIGN KEY (session_id)
        REFERENCES sessions(id),
    CONSTRAINT ck_reviews_rating
        CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recipient_id BIGINT NOT NULL,
    booking_request_id BIGINT,
    type VARCHAR(30) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_notifications_recipient
        FOREIGN KEY (recipient_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_notifications_booking_request
        FOREIGN KEY (booking_request_id)
        REFERENCES booking_requests(id)
        ON DELETE SET NULL,
    CONSTRAINT ck_notifications_type
        CHECK (
            type IN (
                'BOOKING_REQUESTED',
                'BOOKING_ACCEPTED',
                'BOOKING_REJECTED',
                'BOOKING_CANCELLED',
                'SESSION_COMPLETED',
                'REVIEW_RECEIVED'
            )
        ),
    CONSTRAINT ck_notifications_message_not_blank
        CHECK (btrim(message) <> '')
);

CREATE INDEX ix_notifications_recipient_read_created
    ON notifications (recipient_id, is_read, created_at DESC);

CREATE INDEX ix_notifications_booking_request
    ON notifications (booking_request_id)
    WHERE booking_request_id IS NOT NULL;

COMMIT;